ft = input("what fuel type dose your car require")
p = input("is your fuel type premium or regular")
fc = int(input("how much dose your can need to be full"))
ap = int(input("how much do you intend to purchase"))
c = input("is your fuel in gallons or litres")
print("how much does",ft,"per",c)
ac = int(input())
act =(ap*ac)
print(act)
